### PR TITLE
fix passing time dimension instead of dataarray in upsampling

### PR DESCRIPTION
**Pull request by veni-vidi-vici-dormivi**

### CODE REVIEW

**Review by mathause — APPROVED** [review]
Maybe make it explicit?
```python
time_dim = "time"
...
```
but also fine to merge as is.

**Comment by veni-vidi-vici-dormivi** [comment]
You mean implementing a keyword argument in `upsample_yearly_data` and `fit_to_bic_xr` and passing the monthly_data data array (potentially including tas) into upsampling?
I agree that a flexible time dimension would be better.

**Comment by mathause** [comment]
I thought to just write it out for now an let the other be a long term goal

**Comment by veni-vidi-vici-dormivi** [comment]
> let the other be a long term goal
Whoopsie too late. What do you think about this? Then I would change the PR title to "Make time dim explicit in upsampling yearly data".

**Pull request merged**
