### PR TITLE
enforce absolute imports

### PR DESCRIPTION
**Pull request by mathause**
- [ ] Closes #xxx
 - [ ] Tests added
 - [ ] Fully documented, including `CHANGELOG.rst`

### CODE REVIEW

**Review by veni-vidi-vici-dormivi — APPROVED** [review]
Very nice!

**Comment by mathause** [comment]
> Very nice!

Thanks. Why are you working on Sunday? :wink:

**Comment by veni-vidi-vici-dormivi** [comment]
> Thanks. Why are you working on Sunday? 😉

Working on paper reviews 😅 
And you? 💁‍♀️

**Comment by mathause** [comment]
On the train :train:

**Pull request merged**
