### PR TITLE
power transformer: coeffs as array

### PR DESCRIPTION
**Pull request by mathause**
- [ ] Closes #xxx
 - [ ] Tests added
 - [ ] Fully documented, including `CHANGELOG.rst`

This would be a step towards #517 - gather the coeffs in an array instead of different variables. This should make it agnostic to the number of coeffs there are.

What I am not happy is the naming (as always) - the DataArray is now named `coeffs` and it has a dimension named `coeff` - that is not good but would be a good name? :face_in_clouds:

### CODE REVIEW

**Comment by veni-vidi-vici-dormivi** [comment]
Thinking about the fact that we might want to merge all parameters into one dataset in the end we could go for something like pt_parameters.

**Comment by mathause** [comment]
`params` sounds good or maybe `lambda_coeffs`. I thought about naming the dimension `beta` as regression params are often called $\beta$  (breaks down a bit for the constant lambda)

**Comment by veni-vidi-vici-dormivi** [comment]
Hm yeah `lambda_coeffs` is nice. Why not `coeff` as dim? That's also what we have for the harmonic model.

**Comment by mathause** [comment]
> Hm yeah `lambda_coeffs` is nice. Why not `coeff` as dim? That's also what we have for the harmonic model.

Yup - let's go for this - thanks.

**Review by veni-vidi-vici-dormivi — APPROVED** [review]
Cool thanks!

**Comment by veni-vidi-vici-dormivi** [comment]
Thanks!

**Pull request merged**
